include:
  - ./NAS_base/docker-compose.yml

services:
  nas_frontend:
    build:
      context: ./NAS_frontend
    profiles: [frontend]
    ports:
      - "3000:3000"
    environment:
      DRUPAL_BASE_URL: http://nginx
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
    depends_on:
      nginx:
        condition: service_started
        required: false
    networks:
      - nas_net
